In [2]:
import numpy as np

In [2]:
test1 = [92, 94, 88, 91, 87]
test2 = [79, 100, 86, 93, 91]
print(test1+test2)

[92, 94, 88, 91, 87, 79, 100, 86, 93, 91]


In [5]:
print(test1 + 2 )

TypeError: can only concatenate list (not "int") to list

In [8]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
#Numpy Arrays are mutable, which means that you can change the value of an element in the array after an array has been initialized.
print(a[1])

<class 'numpy.ndarray'>
(3,)
2


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [5]:
np.zeros(2)
np.ones(2)
np.empty(5)

array([6.95106072e-310, 6.95106072e-310, 4.94065646e-324,             nan,
       2.37151510e-322])

In [19]:
np.arange(4)
a = np.arange(2,9,2)
a.dtype
print(a)
b = a.reshape(2,2)
print(b)

[2 4 6 8]
[[2 4]
 [6 8]]


In [22]:
np.linspace(0,10, num=10)
np.linspace(-5, 5, 100)
np.arange(-5,6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [23]:
array_example = np.array([[[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0 ,1 ,2, 3],
...                            [4, 5, 6, 7]]])

In [24]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
array_example.size

24

In [26]:
array_example.shape #tensor  #

(3, 2, 4)

In [27]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [28]:
c.shape

(3, 4)

In [3]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [7]:
arrai = np.arange(6)
arrai.shape

(6,)

In [10]:
print(arrai)

[0 1 2 3 4 5]


In [8]:
arraies = arrai[np.newaxis, :]
arraies.shape

(1, 6)

In [9]:
print(arraies)

[[0 1 2 3 4 5]]


In [11]:
arraies2 = arrai[:,np.newaxis]
arraies2.shape

(6, 1)

In [12]:
print(arraies2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a.shape

(3, 4)

In [17]:
print(a[a<6])

[1 2 3 4 5]


In [18]:
less_than_six = (a < 6)
print(a[less_than_six])

[1 2 3 4 5]


In [20]:
divisible_by_two = a[a%2==0]
print(divisible_by_two)

[ 2  4  6  8 10 12]


In [21]:
c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [22]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
condition = (a>5) & (a == 5)
print(condition)

[[False False False False]
 [False False False False]
 [False False False False]]


In [1]:
import os

In [2]:
os.getcwd()

'/home/Ana/my_project'

In [4]:
os.listdir(".")

['Untitled.ipynb',
 '.env',
 'torch_.ipynb',
 'scan.py',
 'Untitled2.ipynb',
 '.ipynb_checkpoints',
 '02machine_learning',
 'cnn_and_lstm-Copy1.ipynb',
 'BERT_24th_Dex.ipynb',
 'Untitled',
 'PCFG.py.lock',
 'temp',
 'squad.py',
 'scan.py.lock',
 '01linear_algebra',
 'cnn_and_lstm.ipynb',
 'squad.py.lock',
 'RNN.ipynb',
 'data',
 '.idea',
 'hugging_data.ipynb',
 'Untitled Folder',
 '.git',
 'PCFG.py']

In [6]:
for x in os.listdir("."):
    if x.endswith('.ipynb'):
        print(x)

Untitled.ipynb
torch_.ipynb
Untitled2.ipynb
cnn_and_lstm-Copy1.ipynb
BERT_24th_Dex.ipynb
cnn_and_lstm.ipynb
RNN.ipynb
hugging_data.ipynb


In [8]:
print(*[file for file in os.listdir('02machine_learning')])

Untitled.ipynb ana_datatypes.ipynb .ipynb_checkpoints ana_class.ipynb [HW10]_Simple_Linear_Regression.ipynb [HW11]_Multiple_linear_regression.ipynb ana_function.ipynb Untitled1.ipynb ana_basic_old.ipynb .git ana_numpy.ipynb


In [2]:
import os
os.getcwd()

'/home/Ana/my_project'

In [10]:
os.chdir('/home/Ana/my_project/01linear_algebra')
os.getcwd()

'/home/Ana/my_project/01linear_algebra'

In [11]:
os.listdir()

['HW2. 나만의 데이터셋 만들기.ipynb',
 '.ipynb_checkpoints',
 'HW7_Practice_5_answer.ipynb',
 'HW3_Practice_1_answer.ipynb',
 'HW7_Practice_5.ipynb',
 'HW4_Practice_2_answer.ipynb',
 'HW5_Practice_3.ipynb',
 'HW8_Practice_6_answer.ipynb',
 'HW6_Practice_4.ipynb',
 '__pycache__',
 'HW5_Practice_3_answer.ipynb',
 'HW1. Python 내장함수와 알고리즘 구현.ipynb',
 'plot_helper.py',
 'HW6_Practice_4_answer.ipynb',
 'HW4_Practice_2.ipynb',
 '.git',
 'HW3_Practice_1.ipynb',
 'Quiz1_Linear algebra.ipynb',
 'HW8_Practice_6.ipynb']

In [15]:
os.path.exists('/home/Ana/my_project/01linear_algebra')

True

In [16]:
os.path.exists('/home/Ana/my_project/01linear_algebrar')

False

In [21]:
os.path.splitext('/home/Ana/my_project/01linear_algebra/HW7_Practice_5.ipynb')

('/home/Ana/my_project/01linear_algebra/HW7_Practice_5', '.ipynb')

In [22]:
path = '/home/Ana/my_project/01linear_algebra'
filename = 'os_test.txt'
os.path.join(path, filename)

'/home/Ana/my_project/01linear_algebra/os_test.txt'

In [25]:
os.listdir()

['HW2. 나만의 데이터셋 만들기.ipynb',
 '.ipynb_checkpoints',
 'HW7_Practice_5_answer.ipynb',
 'HW3_Practice_1_answer.ipynb',
 'HW7_Practice_5.ipynb',
 'HW4_Practice_2_answer.ipynb',
 'HW5_Practice_3.ipynb',
 'HW8_Practice_6_answer.ipynb',
 'HW6_Practice_4.ipynb',
 '__pycache__',
 'HW5_Practice_3_answer.ipynb',
 'HW1. Python 내장함수와 알고리즘 구현.ipynb',
 'plot_helper.py',
 'HW6_Practice_4_answer.ipynb',
 'HW4_Practice_2.ipynb',
 '.git',
 'HW3_Practice_1.ipynb',
 'Quiz1_Linear algebra.ipynb',
 'HW8_Practice_6.ipynb']

In [24]:
os.getcwd()

'/home/Ana/my_project/01linear_algebra'

In [27]:
os.path.dirname('/home/Ana/my_project/01linear_algebra/os_test.txt')

'/home/Ana/my_project/01linear_algebra'

In [28]:
os.path.basename('/home/Ana/my_project/01linear_algebra/os_test.txt')

'os_test.txt'

In [29]:
import sys

In [31]:
print(sys.argv)

['/home/Ana/miniconda3/lib/python3.9/site-packages/ipykernel_launcher.py', '-f', '/home/Ana/.local/share/jupyter/runtime/kernel-b6b5f35e-7741-4b3f-86a7-c414ae6de115.json']


In [32]:
dir(".")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [34]:
os.getcwd()

'/home/Ana/my_project/01linear_algebra'

In [38]:
if 'modern' not in 'heaily modern':
    print('there is no s')
else:
    print('there is modern')

there is modern


In [42]:
id('moden')

139743465141168

In [43]:
id('modern')

139743465143536

In [45]:
'alice' in ['true','bomb ', 'haddington']

False

In [46]:
text = 'string'
print(list(text))

['s', 't', 'r', 'i', 'n', 'g']


In [47]:
for x in text:
	print(list(x))

['s']
['t']
['r']
['i']
['n']
['g']


In [48]:
a = 3

In [49]:
id(a)

139744206109040

In [50]:
a += 1 

In [51]:
id(a)

139744206109072

In [52]:
my_list = [1,2,3]
id(my_list)

139743465141696

In [53]:
my_list.append(5)
id(my_list)

139743465141696