교차검증과 그리드 서치

In [27]:
import pandas as pd
import numpy as np
wine = pd.read_csv('http://bit.ly/wine_csv_data')
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform, randint

In [3]:
data = wine[['alcohol','sugar','pH']].to_numpy()
target = wine['class'].to_numpy()

In [4]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size = 0.2, random_state = 42)

In [5]:
# split train set into train set and  validation set
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size = 0.2, random_state=42)

In [7]:
print(train_input.shape, test_input.shape)
print(sub_input.shape, val_input.shape) #5,197개 이던 게 4,157로 줄고 검증 데이터는 1,040개 

(5197, 3) (1300, 3)
(4157, 3) (1040, 3)


In [9]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
# training set
print(dt.score(sub_input, sub_target))
# validation set
print(dt.score(val_input, val_target))
# overfitting -> k-fold cross validatio

0.9971133028626413
0.864423076923077


In [11]:
scores = cross_validate(dt, train_input, train_target)
print(scores)

{'fit_time': array([0.00590658, 0.00542927, 0.00577402, 0.00573587, 0.00537157]), 'score_time': array([0.00071383, 0.00063443, 0.00059938, 0.00060749, 0.00062561]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}


In [14]:
print(np.mean(scores['test_score']))

0.855300214703487


In [17]:
scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(scores['test_score']))

0.855300214703487


In [23]:
params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)
dt = gs.best_estimator_
print(dt.score(train_input, train_target))
print(gs.best_params_)
print(gs.cv_results_['mean_test_score'])

0.9615162593804117
{'min_impurity_decrease': 0.0001}
[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [28]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [30]:
rgen = randint(0, 10)
rgen.rvs(10)

array([7, 2, 8, 9, 9, 0, 6, 3, 0, 4])

In [31]:
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([104,  84, 117,  98,  97, 119,  98, 107,  85,  91]))